console.log("Hello World")
console.log("Nama : Nazwa Az Zahra")
console.log("Jenis Kelamin : Perempuan")
console.log("Tempat, Tanggal lahir : Bandung,02 Agustus 2006")
console.log("Agama : Islam")
console.log("Alamat : Komplek Permata Kopo Blok F 76")
console.log("Hobi : Banyak")
console.log("Cita-cita : Dokter dan Ahli biomedis")
console.log("Nama pacar : Ada digantungan tas")